import Head from 'next/head';
import { ApolloProvider } from '@apollo/client';
import client from '../lib/apolloClient';
import ProductList from '../components/ProductList';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <ApolloProvider client={client}>
                <main className="min-h-screen bg-gray-50 p-8">
                    <div className="max-w-7xl mx-auto">
                        <header className="mb-8 text-center">
                            <h1 className="text-4xl font-extrabold text-gray-900 mb-2">Multigrain Atta Store</h1>
                            <p className="text-gray-600 max-w-2xl mx-auto">Discover our premium range of healthy, nutrient-rich flours for your daily needs.</p>
                        </header>

                        <ProductList />
                    </div>
                </main>
            </ApolloProvider>
        </>
    );
}
